#Available checks: content_scanning, schema_validation, deduplication
#Using any other name would result in your configuration being invalid

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://centos-dbftp:5432/dataingestion
    username: dataingestion
    password: dataingestion
configuration:
  original_source: 'C:\Users\m.koskinas\Desktop\SampleFiles'
  output: output
  checks:
    content_scanning:
      status: true
      input: original_source
      output: schema_validation
    schema_validation:
      status: true
      input: content_scanning
      output: deduplication
    deduplication:
      status: true
      input: content_scanning
      output: output


